translat ES

diff --git a/docs/src/checkref b/docs/src/checkref
--- a/docs/src/checkref
+++ b/docs/src/checkref
@@ -12,8 +12,8 @@ shift
 
 FILES="$@"
 
-if [ -z $(which checklink) ]; then
-    echo "ERROR: no se encontró checklink, instale w3c-linkchecker para la validación de enlaces HTML" 1>&2
+if [ -z $(which linuxcnc-checklink) ]; then
+    echo "ERROR: checklink no encontrado, instalar w3c-linkchecker para validacion de links HTML" 1>&2
     exit 1
 fi
 
@@ -22,8 +22,8 @@ BAD_LINKS=0
 for F in $FILES; do
     OUT=.checklink.$LANGUAGE.$(basename $F).tmp
     rm -f $OUT
-    checklink --quiet --exclude "http(s?)://" $F | tee $OUT 2>&1
-    egrep -q 'List of (broken links and other issues|duplicate and empty anchors)' $OUT
+    linuxcnc-checklink --quiet --exclude "http(s?)://" $F | tee $OUT 2>&1
+    egrep -q 'Lista de (links rotos y otros asuntos|anclajes duplicados y vacios)' $OUT
     if [ $? -ne 1 ]; then
         BAD_LINKS=1
     fi
@@ -33,9 +33,9 @@ done
 if [ $BAD_LINKS -eq 1 ]; then
     RET_VAL=1
     echo "***" 1>&2
-    echo "*** aviso: links incorrectos encontrados en documentos $LANGUAGE !" 1>&2
+    echo "*** Atencion: links incorrectos en documentos $LANGUAGE !" 1>&2
     if [ $WARN_ON_FAILURE -eq 1 ]; then
-        echo "*** oh bien, continuando de todas formas" 1>&2
+        echo "*** de acuerdo, continuo de todas formas" 1>&2
         RET_VAL=0
     fi
     echo "***" 1>&2
@@ -43,7 +43,9 @@ if [ $BAD_LINKS -eq 1 ]; then
 else
     echo "###"
     echo "### lenguaje: $LANGUAGE"
-    echo "### todos los links correctos!"
+    echo "### todos los links son correctos!"
     echo "###"
+fi
+
 fi
 
